---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      # Replace tabs by whitespaces before committing
      - id: remove-tabs
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff-check
        args: [ --fix, --exit-non-zero-on-fix ]
  # No official hook yet
  - repo: https://github.com/NSPBot911/ty-pre-commit
    rev: v0.0.25
    hooks:
      - id: ty-check
        language: system
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.1
    hooks:
      - id: uv-lock
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
        language: system
  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.15.0
    hooks:
      - id: markdownlint
        args: [ --style, ./.mdl_style.rb ]
        language_version: system
  - repo: https://github.com/repo-helper/pyproject-parser
    rev: v0.14.0
    hooks:
      - id: check-pyproject
      - id: reformat-pyproject
  - repo: https://github.com/yunojuno/pre-commit-xenon
    rev: v0.1
    hooks:
      - id: xenon
        args: [ "--max-average=A", "--max-modules=B", "--max-absolute=B" ]
#  - repo: https://github.com/seddonym/import-linter
#    rev: v2.11
#    hooks:
#      - id: import-linter
#        language: system
