name: Publish

on:
  push:
    tags:
      - 'v*.*.*'
  # workflow_run doesn't appear to be able to combine with publishing on tags
  #workflow_run:
  #  workflows: [ "CI" ]
  #  types: [ completed ]

jobs:
  release:
    runs-on: ubuntu-latest
    # TODO: only run this if the CI job succeeds and there is a tag set
    #if: github.event.workflow_run.conclusion == 'success'
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    strategy:
      matrix:
        python-version:
          - 3.9
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get -y install graphviz
        python -m pip install --upgrade pip
        pip install wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build package
      run: |
        python -m build
        twine check dist/*
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
